@Web_HostAddress = http://localhost:5191

@n_r = 50
GET {{Web_HostAddress}}/Fibonacci/recursive/{{n_r}}
Accept: application/json

###
@n_l = 50
GET {{Web_HostAddress}}/Fibonacci/linear/{{n_l}}
Accept: application/json
